package:
  name: pyqstem
  # this is nice, but only works once you have an initial annotated git tag
  # version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}
  version:  0.0.1

source:
  git_url: https://github.com/jacobjma/PyQSTEM
  # git_tag:  (commit id or tag of release to build, defaults to master)
  patches:
    - setup_simplify.patch

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True   # [win and py<35]

requirements:
  build:
    - cython
    - fftw
    - numpy
    - python
    - setuptools
    - toolchain
  run:
    - ase
    - fftw
    - matplotlib
    - numpy
    - python
    - scikit-image
    - scipy

test:
  imports:
    - pyqstem
    - pyqstem.util
    - pyqstem.potentials
